---

- name: install rbenv
  git:
    repo: "{{ rbenv_rbenv_repository }}"
    dest: "{{ rbenv_root }}"
    version: "{{ rbenv_rbenv_version }}"
    accept_hostkey: yes
    umask: "022"
    force: yes

- name: rbenv plugins directory
  file:
    path: "{{ rbenv_root }}/plugins"
    state: directory
    mode: '0755'

- name: install rbenv plugins
  git:
    repo: "{{ lookup('vars', 'rbenv_' + item + '_repository') }}"
    dest: "{{ rbenv_root }}/plugins/{{ item }}"
    version: "{{ lookup('vars', 'rbenv_' + item + '_version') }}"
    accept_hostkey: yes
    umask: "022"
    force: yes
  loop: "{{ rbenv_plugins }}"
