---

- name: "check ruby {{ rbenv_ruby_version }} install"
  shell: "rbenv versions --bare --skip-aliases | grep '^{{ rbenv_ruby_version }}$'"
  environment:
    PATH: "{{ rbenv_root }}/bin:{{ lookup('env', 'PATH') }}"
    RBENV_ROOT: "{{ rbenv_root }}"
  failed_when: false
  changed_when: false
  register: t_rbenv_ruby_installed

- name: "install ruby {{ rbenv_ruby_version }}"
  shell: "rbenv install {{ rbenv_ruby_version }}"
  environment:
    PATH: "{{ rbenv_root }}/bin:{{ lookup('env', 'PATH') }}"
    RBENV_ROOT: "{{ rbenv_root }}"
  when: t_rbenv_ruby_installed.rc != 0

#

- name: "get global version"
  shell: "rbenv global"
  changed_when: false
  failed_when: false
  environment:
    PATH: "{{ rbenv_root }}/bin:{{ lookup('env', 'PATH') }}"
    RBENV_ROOT: "{{ rbenv_root }}"
  register: t_rbenv_global_version

- name: "set global version"
  shell: "rbenv global {{ rbenv_ruby_version }}"
  environment:
    PATH: "{{ rbenv_root }}/bin:{{ lookup('env', 'PATH') }}"
    RBENV_ROOT: "{{ rbenv_root }}"
  when: t_rbenv_global_version.stdout != rbenv_ruby_version
