---

- block:
    - name: guess who am I
      shell: whoami
      register: whoami
      changed_when: no
      check_mode: no

    - name: get my homedir
      shell: "getent passwd {{ whoami.stdout }} | awk -F: '{print $6 }'"
      changed_when: no
      register: rbenv_homedir

    - name: set rbenv_homedir
      set_fact:
        rbenv_root: "{{ rbenv_homedir.stdout }}/.rbenv"

  when: rbenv_root is not defined or rbenv_root == ""

- name: install_rbenv
  include_tasks: install_rbenv.yml

- name: update_profile
  include_tasks: update_profile.yml

- name: install ruby
  include_tasks: install_ruby.yml

- name: install gem
  include_tasks: install_gem.yml




# clone rbenv pull / master
#
#  next if test :gem, :query, '--quiet --installed --name-matches ^bundler$'
# gem install bundler --quiet --no-rdoc --no-ri
